spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devpath;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: test-github-client
            client-secret: test-github-secret
          google:
            client-id: test-google-client
            client-secret: test-google-secret

  data:
    redis:
      host: localhost
      port: 6379
      password:
