-- OCR schema backfill for environments that already have ocr_results rows.
ALTER TABLE ocr_results
    ADD COLUMN IF NOT EXISTS source_image_url VARCHAR(500);

ALTER TABLE ocr_results
    ADD COLUMN IF NOT EXISTS status VARCHAR(30);

ALTER TABLE ocr_results
    ADD COLUMN IF NOT EXISTS searchable_normalized_text TEXT;

ALTER TABLE ocr_results
    ADD COLUMN IF NOT EXISTS timestamp_mappings TEXT;

ALTER TABLE ocr_results
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- Fill defaults before tightening the new non-null columns.
UPDATE ocr_results
SET source_image_url = COALESCE(source_image_url, '')
WHERE source_image_url IS NULL;

UPDATE ocr_results
SET status = COALESCE(status, 'REQUESTED')
WHERE status IS NULL;

UPDATE ocr_results
SET searchable_normalized_text = COALESCE(searchable_normalized_text, LOWER(REGEXP_REPLACE(TRIM(extracted_text), '\s+', ' ', 'g')))
WHERE searchable_normalized_text IS NULL
  AND extracted_text IS NOT NULL;

UPDATE ocr_results
SET timestamp_mappings = COALESCE(
    timestamp_mappings,
    '[{"second":' || COALESCE(frame_timestamp_second, 0) || ',"text":"' ||
    REPLACE(REPLACE(REPLACE(COALESCE(extracted_text, ''), E'\\', E'\\\\'), '"', E'\\"'), E'\n', ' ') ||
    '"}]'
)
WHERE timestamp_mappings IS NULL;

UPDATE ocr_results
SET updated_at = COALESCE(updated_at, created_at, NOW())
WHERE updated_at IS NULL;

ALTER TABLE ocr_results
    ALTER COLUMN source_image_url SET DEFAULT '';

ALTER TABLE ocr_results
    ALTER COLUMN source_image_url SET NOT NULL;

ALTER TABLE ocr_results
    ALTER COLUMN status SET DEFAULT 'REQUESTED';

ALTER TABLE ocr_results
    ALTER COLUMN status SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ocr_results_user_lesson_frame
    ON ocr_results (user_id, lesson_id, frame_timestamp_second);

-- QnA lesson link for opening the exact lecture screen from instructor inbox.
ALTER TABLE qna_questions
    ADD COLUMN IF NOT EXISTS lesson_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_qna_questions_lesson_id
    ON qna_questions (lesson_id);

-- Recommendation support columns for history, warning, and supplement tracking.
ALTER TABLE recommendation_histories
    ADD COLUMN IF NOT EXISTS recommendation_id BIGINT;

ALTER TABLE recommendation_histories
    ADD COLUMN IF NOT EXISTS node_id BIGINT;

ALTER TABLE recommendation_histories
    ADD COLUMN IF NOT EXISTS action_type VARCHAR(30);

UPDATE recommendation_histories
SET action_type = COALESCE(action_type, 'GENERATED')
WHERE action_type IS NULL;

ALTER TABLE recommendation_histories
    ALTER COLUMN action_type SET DEFAULT 'GENERATED';

ALTER TABLE recommendation_histories
    ALTER COLUMN action_type SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_recommendation_histories_user_created_at
    ON recommendation_histories (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_recommendation_histories_user_recommendation_id
    ON recommendation_histories (user_id, recommendation_id);

CREATE INDEX IF NOT EXISTS idx_recommendation_histories_user_node_id
    ON recommendation_histories (user_id, node_id);

ALTER TABLE risk_warnings
    ADD COLUMN IF NOT EXISTS risk_level VARCHAR(20);

ALTER TABLE risk_warnings
    ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMP;

UPDATE risk_warnings
SET risk_level = COALESCE(risk_level, 'MEDIUM')
WHERE risk_level IS NULL;

UPDATE risk_warnings
SET acknowledged_at = COALESCE(acknowledged_at, created_at)
WHERE is_acknowledged = TRUE
  AND acknowledged_at IS NULL;

ALTER TABLE risk_warnings
    ALTER COLUMN risk_level SET DEFAULT 'MEDIUM';

ALTER TABLE risk_warnings
    ALTER COLUMN risk_level SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_risk_warnings_user_created_at
    ON risk_warnings (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_risk_warnings_user_acknowledged
    ON risk_warnings (user_id, is_acknowledged, created_at);

CREATE INDEX IF NOT EXISTS idx_risk_warnings_user_node_id
    ON risk_warnings (user_id, node_id);

CREATE TABLE IF NOT EXISTS roadmap_node_resources (
    resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id BIGINT NOT NULL REFERENCES roadmap_nodes (node_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    description TEXT,
    source_type VARCHAR(30),
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_roadmap_node_resources_node_id
    ON roadmap_node_resources (node_id);

CREATE INDEX IF NOT EXISTS idx_roadmap_node_resources_active
    ON roadmap_node_resources (active);

ALTER TABLE supplement_recommendations
    ADD COLUMN IF NOT EXISTS priority INTEGER;

ALTER TABLE supplement_recommendations
    ADD COLUMN IF NOT EXISTS coverage_percent DOUBLE PRECISION;

ALTER TABLE supplement_recommendations
    ADD COLUMN IF NOT EXISTS missing_tag_count INTEGER;

ALTER TABLE supplement_recommendations
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE supplement_recommendations
SET updated_at = COALESCE(updated_at, created_at, NOW())
WHERE updated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_supplement_recommendations_user_created_at
    ON supplement_recommendations (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_supplement_recommendations_user_node_created_at
    ON supplement_recommendations (user_id, node_id, created_at);

ALTER TABLE user_profiles
    ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE roadmap_hub_items
    ADD COLUMN IF NOT EXISTS icon_color VARCHAR(32);

-- Legacy local PostgreSQL rows can exist without these newer columns.
UPDATE lesson_progress
SET is_pip_enabled = COALESCE(is_pip_enabled, FALSE)
WHERE EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'lesson_progress'
      AND column_name = 'is_pip_enabled'
)
  AND is_pip_enabled IS NULL;

UPDATE tags
SET is_deleted = COALESCE(is_deleted, FALSE)
WHERE EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'tags'
      AND column_name = 'is_deleted'
)
  AND is_deleted IS NULL;

UPDATE refund_request rr
SET instructor_id = COALESCE(rr.instructor_id, c.instructor_id)
FROM courses c
WHERE rr.course_id = c.course_id
  AND EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_name = 'refund_request'
        AND column_name = 'instructor_id'
  )
  AND rr.instructor_id IS NULL;

UPDATE refund_request
SET enrolled_at = COALESCE(enrolled_at, requested_at, processed_at, NOW())
WHERE EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'refund_request'
      AND column_name = 'enrolled_at'
)
  AND enrolled_at IS NULL;

UPDATE refund_request
SET progress_percent_snapshot = COALESCE(progress_percent_snapshot, 0)
WHERE EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'refund_request'
      AND column_name = 'progress_percent_snapshot'
)
  AND progress_percent_snapshot IS NULL;

UPDATE refund_request rr
SET refund_amount = COALESCE(rr.refund_amount, CAST(c.price AS BIGINT), 0)
FROM courses c
WHERE rr.course_id = c.course_id
  AND EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_name = 'refund_request'
        AND column_name = 'refund_amount'
  )
  AND rr.refund_amount IS NULL;

UPDATE refund_request
SET is_deleted = COALESCE(is_deleted, FALSE)
WHERE EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'refund_request'
      AND column_name = 'is_deleted'
)
  AND is_deleted IS NULL;

-- Workspace team file room metadata and folder support.
ALTER TABLE workspace_file
    ADD COLUMN IF NOT EXISTS parent_id BIGINT;

ALTER TABLE workspace_file
    ADD COLUMN IF NOT EXISTS item_type VARCHAR(20);

ALTER TABLE workspace_file
    ADD COLUMN IF NOT EXISTS storage_provider VARCHAR(50);

ALTER TABLE workspace_file
    ADD COLUMN IF NOT EXISTS object_key VARCHAR(1000);

ALTER TABLE workspace_file
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE workspace_file
SET item_type = 'FILE'
WHERE item_type IS NULL;

UPDATE workspace_file
SET storage_provider = 'LOCAL'
WHERE storage_provider IS NULL;

UPDATE workspace_file
SET updated_at = COALESCE(created_at, NOW())
WHERE updated_at IS NULL;

ALTER TABLE workspace_file
    ALTER COLUMN item_type SET DEFAULT 'FILE';

ALTER TABLE workspace_file
    ALTER COLUMN item_type SET NOT NULL;

ALTER TABLE workspace_file
    ALTER COLUMN storage_provider SET DEFAULT 'LOCAL';

ALTER TABLE workspace_file
    ALTER COLUMN storage_provider SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_workspace_file_workspace_parent
    ON workspace_file (workspace_id, parent_id, is_deleted, item_type, created_at DESC);

DO $$
BEGIN
    IF to_regclass('public.voice_channels') IS NULL OR to_regclass('public.users') IS NULL THEN
        RETURN;
    END IF;

    ALTER TABLE public.voice_channels
        ADD COLUMN IF NOT EXISTS current_session_started_at TIMESTAMP;

    CREATE TABLE IF NOT EXISTS public.voice_lobby_presence (
        voice_lobby_presence_id BIGSERIAL PRIMARY KEY,
        voice_channel_id BIGINT NOT NULL REFERENCES public.voice_channels(voice_channel_id),
        user_id BIGINT NOT NULL REFERENCES public.users(user_id),
        last_seen_at TIMESTAMP NOT NULL DEFAULT NOW(),
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        CONSTRAINT uk_voice_lobby_presence_channel_user UNIQUE (voice_channel_id, user_id)
    );

    CREATE INDEX IF NOT EXISTS idx_voice_lobby_presence_channel_seen
        ON public.voice_lobby_presence (voice_channel_id, last_seen_at);

    CREATE TABLE IF NOT EXISTS public.voice_chat_messages (
        voice_chat_message_id BIGSERIAL PRIMARY KEY,
        voice_channel_id BIGINT NOT NULL REFERENCES public.voice_channels(voice_channel_id),
        sender_id BIGINT NOT NULL REFERENCES public.users(user_id),
        content TEXT NOT NULL,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_voice_chat_messages_channel_created
        ON public.voice_chat_messages (voice_channel_id, created_at);

    CREATE TABLE IF NOT EXISTS public.voice_chat_clear_states (
        voice_chat_clear_state_id BIGSERIAL PRIMARY KEY,
        voice_channel_id BIGINT NOT NULL REFERENCES public.voice_channels(voice_channel_id),
        user_id BIGINT NOT NULL REFERENCES public.users(user_id),
        cleared_at TIMESTAMP NOT NULL DEFAULT NOW(),
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
        CONSTRAINT uk_voice_chat_clear_state_channel_user UNIQUE (voice_channel_id, user_id)
    );

    CREATE INDEX IF NOT EXISTS idx_voice_chat_clear_state_channel_user
        ON public.voice_chat_clear_states (voice_channel_id, user_id);

    CREATE TABLE IF NOT EXISTS public.voice_meeting_minutes (
        voice_meeting_minutes_id BIGSERIAL PRIMARY KEY,
        voice_channel_id BIGINT NOT NULL UNIQUE REFERENCES public.voice_channels(voice_channel_id),
        updated_by_user_id BIGINT NOT NULL REFERENCES public.users(user_id),
        recording BOOLEAN NOT NULL DEFAULT FALSE,
        transcript TEXT,
        summary TEXT,
        is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
END $$;
